export const categories = [
  {
    value: "All Categories",
    label: "All Categories",
  },
  {
    value: "Vehicles",
    label: "Vehicles",
  },
  {
    value: "Property",
    label: "Property",
  },
  {
    value: "Electronics",
    label: "Electronics",
  },
  {
    value: "Business & Services",
    label: "Business & Services",
  },
];

export const regions = [
  {
    value: "Select a Region",
    label: "Select a Region",
  },
  {
    value: "Ampara",
    label: "Ampara",
  },
  {
    value: "Kegalle",
    label: "Kegalle",
  },
  {
    value: "Colombo",
    label: "Colombo",
  },
  {
    value: "Avissawella",
    label: "Avissawella",
  },
];
export const categoryType = [
  {
    id: 1,
    title: "Vehicles",
    total: 7235,
  },
  {
    id: 2,
    title: "Property",
    total: 4100,
  },
  {
    id: 3,
    title: "Electronics",
    total: 2231,
  },
  {
    id: 4,
    title: "Business & Services",
    total: 1245,
  },
];

export const vehicleCategories = [
  { id: 1, name: "All", isChecked: true },
  { id: 2, name: "Cars", isChecked: false },
  { id: 3, name: "Buses", isChecked: false },
  { id: 4, name: "Car Parts", isChecked: false },
  { id: 5, name: "Boats", isChecked: false },
  { id: 6, name: "Lorries", isChecked: false },
  { id: 7, name: "Motorcycles", isChecked: false },
  { id: 8, name: "Three Wheelers", isChecked: false },
  { id: 9, name: "Tractors", isChecked: false },
  { id: 10, name: "SUVs/Jeeps", isChecked: false },
  { id: 11, name: "Vans", isChecked: false },
  { id: 12, name: "Other", isChecked: false },
];

export const vehicleAdds = [
  {
    id: 2,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Mercedes Benz ML320",
    date: "2021-08-19",
    category: "Cars",
    user: "Sandun",
    image: [
      "http://patpat-s3-live.s3.amazonaws.com/uploads/30ab9e94924fbbd7efa6682bbce08a29-710100.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    modelYear: 2017,
    condition: "Used",
    transmission: "Automatic",
    manufacturer: "BMW",
    model: "I8",
    fuelType: "Petrol",
    engineCapacity: "1500 CC",
    mileage: "30000 km",
    color: "White",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 3,
    categoryId: 3,
    AdReference: "W4018081744961202101",
    amount: 4990000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Mercedes Benz ML320",
    date: "2021-08-19",
    category: "Buses",
    user: "Sandun",
    image: [
      "http://patpat-s3-live.s3.amazonaws.com/uploads/18df56ed56c5471cbcd41fecbf6a5087-367635.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/0dbef7ac65c873b2a3e80019548b3c3a-226162.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/c7e71e1c821328a71e0612e7f07d5236-195630.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/65b51a60ffbd91121104e255c2c5d3f2-875768.jpeg",
    ],
    modelYear: 2017,
    condition: "Used",
    transmission: "Automatic",
    manufacturer: "BMW",
    model: "I8",
    fuelType: "Petrol",
    engineCapacity: "1500 CC",
    mileage: "30000 km",
    color: "White",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 4,
    categoryId: 3,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Mercedes Benz ML320",
    date: "2021-08-19",
    category: "Buses",
    user: "Sandun",
    image: [
      "http://patpat-s3-live.s3.amazonaws.com/uploads/30ab9e94924fbbd7efa6682bbce08a29-710100.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    modelYear: 2017,
    condition: "Used",
    transmission: "Automatic",
    manufacturer: "BMW",
    model: "I8",
    fuelType: "Petrol",
    engineCapacity: "1500 CC",
    mileage: "30000 km",
    color: "White",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 5,
    categoryId: 4,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Mercedes Benz ML320",
    date: "2021-08-19",
    category: "Car Parts",
    user: "Sandun",
    image: [
      "http://patpat-s3-live.s3.amazonaws.com/uploads/30ab9e94924fbbd7efa6682bbce08a29-710100.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    modelYear: 2017,
    condition: "Used",
    transmission: "Automatic",
    manufacturer: "BMW",
    model: "I8",
    fuelType: "Petrol",
    engineCapacity: "1500 CC",
    mileage: "30000 km",
    color: "White",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 6,
    categoryId: 5,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Mercedes Benz ML320",
    date: "2021-08-19",
    category: "Boats",
    user: "Sandun",
    image: [
      "http://patpat-s3-live.s3.amazonaws.com/uploads/30ab9e94924fbbd7efa6682bbce08a29-710100.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    modelYear: 2017,
    condition: "Used",
    transmission: "Automatic",
    manufacturer: "BMW",
    model: "I8",
    fuelType: "Petrol",
    engineCapacity: "1500 CC",
    mileage: "30000 km",
    color: "White",
    district:"Kegalle",
    town:"Galigamuwa"
  },
];




export const propertyCategories = [
  { id: 1, name: "All", isChecked: true },
  { id: 2, name: "House", isChecked: false },
  { id: 3, name: "Rooms & Anexes", isChecked: false },
  { id: 4, name: "Vacation Rentals", isChecked: false },
  { id: 5, name: "Land", isChecked: false },
  { id: 6, name: "Office - Commercial property", isChecked: false },
];



export const propertyAdds = [
  {
    id: 2,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 55000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Luxury Apartment In Nugegoda",
    area:"1000sqft",
    date: "2021-08-19",
    category: "Houses - Apartments",
    user: "Nirmal",
    image: [
      "http://riyapola.com/oc-content/uploads/156/5243.jpg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 3,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 55000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Luxury Apartment In Nugegoda",
    date: "2021-08-19",
    category: "Houses - Apartments",
    user: "Nirmal",
    image: [
      "http://riyapola.com/oc-content/uploads/156/5243.jpg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 4,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 55000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Luxury Apartment In Nugegoda",
    date: "2021-08-19",
    category: "Houses - Apartments",
    user: "Nirmal",
    image: [
      "http://riyapola.com/oc-content/uploads/156/5243.jpg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 5,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 55000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Luxury Apartment In Nugegoda",
    date: "2021-08-19",
    category: "Houses - Apartments",
    user: "Nirmal",
    image: [
      "http://riyapola.com/oc-content/uploads/156/5243.jpg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 6,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 55000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Luxury Apartment In Nugegoda",
    date: "2021-08-19",
    category: "Houses - Apartments",
    user: "Nirmal",
    image: [
      "http://riyapola.com/oc-content/uploads/156/5243.jpg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/1f63bd17059ace50b7982bd0baa6e2c0-500989.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/bfd44090953c5a677f29f39288ad5287-786302.jpeg",
      "http://patpat-s3-live.s3.amazonaws.com/uploads/a69a81605b7fe37054dea26571ce94e2-842121.jpeg",
    ],
    district:"Kegalle",
    town:"Galigamuwa"
  },
];
export const serviceCategories = [
  { id: 1, name: "All", isChecked: true },
  { id: 2, name: "BabySitter-Nanny", isChecked: false },
  { id: 3, name: "Computer", isChecked: false },
  { id: 4, name: "Health-Beauty-Fitness", isChecked: false },
  { id: 5, name: "Household-Domestric Help", isChecked: false },
  { id: 6, name: "Industry Tools & Machinery", isChecked: false },
  { id: 7, name: "Repair", isChecked: false },
  { id: 8, name: "Supplier & Manufacturers", isChecked: false },
  { id: 9, name: "Even Services", isChecked: false },
  { id: 10, name: "Other", isChecked: false },
];
export const serviceAdds = [
  {
    id: 2,
    categoryId: 2,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Baby Day Care Center",
    date: "2021-08-19",
    category: "BabySitter-Nanny",
    user: "Sandun",
    image: [
      "https://cdn.britannica.com/24/141224-050-0F5FA19C/Caregivers-children-day-care-centre.jpg",
      "https://miro.medium.com/max/1838/1*4Qq39HKxFJi1519BlmDD0A.jpeg",
      "https://www.ifc.org/wps/wcm/connect/62e2ca29-8e46-4cdf-8ff4-e32a1871f530/2/Brandix.JPG?MOD=AJPERES",
   
    ],
    ratings:"5 stars",
    description:"Lets your child fly. Most Popular DayCare Center and Care your babies like ours. We make them happy",
    district:"Colombo",
    town:"Kottawa"
  },
  {
    id: 3,
    categoryId: 3,
    AdReference: "W4018081744961202101",
    amount: 4990000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Laptop.lk",
    date: "2021-08-19",
    category: "Computer",
    user: "Sandun",
    image: [
      "https://www.laptop.lk/wp-content/uploads/2020/11/footer.jpg",
      "https://www.laptop.lk/wp-content/uploads/2020/11/FB-POST-2-300x300.jpg",
      "https://www.laptop.lk/wp-content/uploads/2021/05/ASUS-TUF-Gaming-Dash-F15-300x300.jpg",
      
    ],
    ratings:"5 stars",
    description:"“Laptop.lk” is one of the leading IT retail companies in Sri Lanka. Since its inception in 1996, Laptop.lk has become synonymous with all computer needs, both online & in-store.",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 4,
    categoryId: 4,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Ammu Beauty Care",
    date: "2021-08-19",
    category: "Health-Beauty-Fitness",
    user: "Sandun",
    image: [
      "https://i1.wp.com/classifylanka.com/wp-content/uploads/2021/01/Salon-hisa-care-hair-cut.jpg?fit=960%2C649&ssl=1",
      "https://dminteriors.lk/wp-content/uploads/2019/01/salon-interior-design-in-sri-lanka.jpg",
      "http://saloninsrilanka.weebly.com/uploads/1/1/3/0/113028645/kk_1_orig.jpg",
     
    ],
    ratings:"5 star",
    description:"Over the years, Ammu Beauty Care has become synonymous with premium hair styling services in the city of Navinna. We offers great styling and grooming services and bring out your inner beauty and execute on all your requirements.",
    district:"Corlombo",
    town:"Kollupitiya"
  },
  {
    id: 5,
    categoryId: 5,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Domestic Workers Agency",
    date: "2021-08-19",
    category: "Household-Domestric Help",
    user: "Sandun",
    image: [
      "https://www.carekleen.lk/wp-content/uploads/2020/01/carekleen-social-img.jpg",
      "https://www.carekleen.lk/wp-content/themes/carekleen/img/carekleen-cleaning-company-in-sri-lanka-slider-2.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNn9IAxhrqqdSzqCsvLqzWNEGhOs73r8qypA&usqp=CAU",
  
    ],
    ratings:"4 stars",
    description:"We provide best services with affordable price",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 6,
    categoryId: 6,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Japan EH12 Wacker Rammer",
    date: "2021-08-19",
    category: "Industry Tools & Machinery",
    user: "Sandun",
    image: [
      "https://i.ikman-st.com/0f07be81-2768-40ed-97f8-8eefaba9f177/620/466/fitted.jpg",
      "https://i.ikman-st.com/b2b088b2-a054-4e40-b42f-3245bd4a0963/780/585/fitted.jpg",
      "https://i.ikman-st.com/511c6c04-67e2-405d-9008-572c0c877b20/780/585/fitted.jpg",
      
    ],
    ratings:"Reconditioned",
    description:"Direct Imported Japan Wacker Machines,Original Conditions Are 100% ",
    district:"Kegalle",
    town:"Galigamuwa"
  },
  {
    id: 7,
    categoryId: 4,
    AdReference: "W4018081744961202101",
    amount: 925000,
    leaseRental: 84996,
    downPayment: 107000,
    name: "Tharu Beauty Care",
    date: "2021-08-19",
    category: "Health-Beauty-Fitness",
    user: "Sandun",
    image: [
      "https://i1.wp.com/classifylanka.com/wp-content/uploads/2021/01/Salon-hisa-care-hair-cut.jpg?fit=960%2C649&ssl=1",
      "https://dminteriors.lk/wp-content/uploads/2019/01/salon-interior-design-in-sri-lanka.jpg",
      "http://saloninsrilanka.weebly.com/uploads/1/1/3/0/113028645/kk_1_orig.jpg",
     
    ],
    ratings:"5 star",
    description:"Over the years, Ammu Beauty Care has become synonymous with premium hair styling services in the city of Navinna. We offers great styling and grooming services and bring out your inner beauty and execute on all your requirements.",
    district:"Vavuniya",
    town:"Vavuniya"
  },
];

//electronic data
export const electronicCategories = [
  { id: 1, name: "All", isChecked: true },
  { id: 2, name: "Cell phones-Accessories", isChecked: false },
  { id: 3, name: "Cameras", isChecked: false },
  { id: 4, name: "Audio & MP3", isChecked: false },
  { id: 5, name: "Kitchen, Home Applianas", isChecked: false },
  { id: 6, name: "Laptops, Desktops & Hardware", isChecked: false },
  { id: 7, name: "Networking, WiFi, & CCTV", isChecked: false },
  { id: 8, name: "Software", isChecked: false },
  { id: 9, name: "TVs", isChecked: false },
  { id: 10, name: "Video games", isChecked: false },
  { id: 11, name: "Other", isChecked: false },
];
export const electronicAdds = [

  {
    id: 2,
    categoryId: 2,
    AdReference: "W4018081744961202500",
    amount: 280000,
    leaseRental: 280000,
    downPayment: 270000,
    name: "iPhone 12 Pro Max",
    date: "2021-08-19",
    category: "Mobile Phones",
    user: "Izam",
    image: [
      "https://idealz.lk/wp-content/uploads/2020/10/12-Pro-Max-Blue.jpg",
      "https://idealz.lk/wp-content/uploads/2020/10/12-Pro-Max-Gold.jpg",
      "https://idealz.lk/wp-content/uploads/2020/10/12-Pro-Max-Silver.jpg",
      "https://idealz.lk/wp-content/uploads/2020/10/12-Pro-Max-Grey.jpg",
    ],
    condition: "New",
    manufacturer: "Apple",
    model: "12 Pro MaX 256GB 6GB",
    color: "Silver, Graphite, Gold, Pacific Blue",
    district:"Gampha",
    town:"Kadawatha"
  },

];


export const districts = [
  {id:1, value: "Colombo", label: "Colombo" },
  {id:2, value: "Kalutara", label: "Kalutara" },
  {id:3, value: "Gampaha", label: "Gampaha" },
  {id:4, value: "Rathnapura", label: "Rathnapura" },
  {id:5, value: "Jaffna", label: "Jaffna" },
  {id:6, value: "Kilinochchi", label: "Kilinochchi" },
  {id:7, value: "Mannar", label: "Mannar" },
  {id:8, value: "Mullaitiv", label: "Mullaitiv" },
  {id:9, value: "Puttalam", label: "Puttalam" },
  {id:10, value: "Vavuniya", label: "Vavuniya" },
  {id:11, value: "Kurunegala", label: "Kurunegala" },
  {id:12, value: "Anuradhapura", label: "Anuradhapura" },
  {id:13, value: "Polonnaruwa", label: "Polonnaruwa" },
  {id:14, value: "Matale", label: "Matale" },
  {id:15, value: "Kandy", label: "Kandy" },
  {id:16, value: "Nuwara Eliya", label: "Nuwara Eliya" },
  {id:17, value: "Kegalle", label: "Kegalle" },
  {id:18, value: "Trincomalee", label: "Trincomalee" },
  {id:19, value: "Batticaloa", label: "Batticaloa" },
  {id:20, value: "Ampara", label: "Ampara" },
  {id:21, value: "Monaragala", label: "Monaragala" },
  {id:22, value: "Badulla", label: "Badulla" },
  {id:23, value: "Hambantota", label: "Hambantota" },
  {id:24, value: "Matara", label: "Matara" },
  {id:25, value: "Galle", label: "Galle" },
]


export const areas = [
  {id:1,mainCategory:1,value:"Avissawella",label:"Avissawella"},
  {id:2,mainCategory:3,value:"Mirigama",label:"Mirigama"},
  {id:3,mainCategory:2,value:"Kalutara",label:"Kalutara"},
  {id:4,mainCategory:4,value:"Eheliyagodata",label:"Eheliyagodata"},
  {id:5,mainCategory:4,value:"Pelmadulla",label:"Pelmadulla"},
  {id:6,mainCategory:4,value:"Kuruwita",label:"Kuruwita"},
  {id:7,mainCategory:4,value:"Godakawela",label:"Godakawela"},
  {id:8,mainCategory:4,value:"Kahawatta",label:"Kahawatta"},
  {id:9,mainCategory:4,value:"Weligepola",label:"Weligepola"},
  {id:10,mainCategory:4,value:"Nivitigala",label:"Nivitigala"},
  {id:11,mainCategory:4,value:"Ayagama",label:"Ayagama"},
  {id:12,mainCategory:4,value:"Kalawana",label:"Kalawana"},
  {id:13,mainCategory:4,value:"Kolonne",label:"Kolonne"},
  {id:14,mainCategory:4,value:"Panamure",label:"Panamure"},
  {id:15,mainCategory:4,value:"Opanayaka",label:"Opanayaka"},
  {id:16,mainCategory:1,value:"Dehiwala",label:"Dehiwala"},
  {id:17,mainCategory:1,value:"Homagama",label:"Homagama"},
  {id:18,mainCategory:1,value:"Kaduwela",label:"Kaduwela"},
  {id:19,mainCategory:1,value:"Kesbewa",label:"Kesbewa"},
  {id:20,mainCategory:1,value:"Kolonnawa",label:"Kolonnawa"},
  {id:21,mainCategory:1,value:"Maharagama",label:"Maharagama"},
  {id:22,mainCategory:1,value:"Moratuwa",label:"Moratuwa"},
  {id:23,mainCategory:1,value:"Ratmalana",label:"Ratmalana"},
  {id:24,mainCategory:1,value:"Seethawaka",label:"Seethawaka"},
  {id:25,mainCategory:1,value:"Sri Jayawardenepura Kotte",label:"Sri Jayawardenepura Kotte"},
  {id:26,mainCategory:1,value:"Thibirigasyaya",label:"Thibirigasyaya"},
  {id:27,mainCategory:2,value:"Agalawatta",label:"Agalawatta"},
  {id:28,mainCategory:2,value:"Bandaragama",label:"Bandaragama"},
  {id:29,mainCategory:2,value:"Beruwala",label:"Beruwala"},
  {id:30,mainCategory:2,value:"Bulathsinhala",label:"Bulathsinhala"},
  {id:31,mainCategory:2,value:"Dodangoda",label:"Dodangoda"},
  {id:32,mainCategory:2,value:"Horana",label:"Horana"},
  {id:33,mainCategory:2,value:"Ingiriya",label:"Ingiriya"},
  {id:34,mainCategory:2,value:"Kalutara",label:"Kalutara"},
  {id:35,mainCategory:2,value:"Madurawela",label:"Madurawela"},
  {id:36,mainCategory:2,value:"Matugama",label:"Matugama"},
  {id:37,mainCategory:2,value:"Panadura",label:"Panadura"},
  {id:39,mainCategory:3,value:"Attanagalla",label:"Attanagalla"},
  {id:40,mainCategory:3,value:"Biyagama",label:"Biyagama"},
  {id:41,mainCategory:3,value:"Dompe",label:"Dompe"},
  {id:42,mainCategory:3,value:"Ja-Ela",label:"Ja-Ela"},
  {id:43,mainCategory:3,value:"Kelaniya",label:"Kelaniya"},
  {id:44,mainCategory:3,value:"Negombo",label:"Negombo"},
  {id:45,mainCategory:3,value:"Wattala",label:"Wattala"},
  {id:46,mainCategory:5,value:"Karainagar",label:"Karainagar"},
  {id:47,mainCategory:5,value:"Nallur",label:"Nallur"},
  {id:48,mainCategory:5,value:"Thenmarachchi",label:"Thenmarachchi"},
  {id:49,mainCategory:5,value:"Valikamam",label:"Valikamam"},
  {id:50,mainCategory:6,value:"Kandavalai",label:"Kandavalai"},
  {id:51,mainCategory:6,value:"Karachchi",label:"Karachchi"},
  {id:52,mainCategory:6,value:"Poonakary",label:"Poonakary"},
  {id:53,mainCategory:7,value:"Madhu",label:"Madhu"},
  {id:54,mainCategory:7,value:"Mannar",label:"Mannar"},
  {id:55,mainCategory:7,value:"Musali",label:"Musali"},
  {id:56,mainCategory:7,value:"Nanaddan",label:"Nanaddan"},
  {id:57,mainCategory:8,value:"Oddusuddan",label:"Oddusuddan"},
  {id:58,mainCategory:8,value:"Manthai",label:"Manthai"},
  {id:59,mainCategory:8,value:"Thunukkai",label:"Thunukkai"},
  {id:60,mainCategory:9,value:"Anamaduwa",label:"Anamaduwa"},
  {id:61,mainCategory:9,value:"Battuluoya",label:"Battuluoya"},
  {id:62,mainCategory:9,value:"Dankotuwa",label:"Dankotuwa"},
  {id:63,mainCategory:9,value:"Kalpitiya",label:"Kalpitiya"},
  {id:64,mainCategory:9,value:"Marawila",label:"Marawila"},
  {id:65,mainCategory:9,value:"Wennappuwa",label:"Wennappuwa"},
  {id:66,mainCategory:10,value:"Cheddikulam",label:"Cheddikulam"},
  {id:67,mainCategory:10,value:"Nedunkeni",label:"Nedunkeni"},
  {id:68,mainCategory:10,value:"Vavuniya",label:"Vavuniya"},
  {id:69,mainCategory:11,value:"Giriulla",label:"Giriulla"},
  {id:70,mainCategory:11,value:"Panagamuwa",label:"Panagamuwa"},
  {id:71,mainCategory:11,value:"Pannala",label:"Pannala"},
  {id:72,mainCategory:11,value:"Wariyapola",label:"Wariyapola"},
  {id:73,mainCategory:11,value:"Bingiriya",label:"Bingiriya"},
  {id:74,mainCategory:11,value:"Patuhena",label:"Patuhena"},
  {id:75,mainCategory:12,value:"Eppawala",label:"Eppawala"},
  {id:76,mainCategory:12,value:"Kekirawa",label:"Kekirawa"},
  {id:77,mainCategory:12,value:"Mihintale",label:"Mihintale"},
  {id:78,mainCategory:12,value:"Mihintale",label:"Mihintale"},
  {id:79,mainCategory:12,value:"Kebitigollawa",label:"Kebitigollawa"},
  {id:80,mainCategory:12,value:"Horawupotana",label:"Horawupotana"},
  {id:81,mainCategory:13,value:"Aralaganwila",label:"Aralaganwila"},
  {id:82,mainCategory:13,value:"Elahena",label:"Elahena"},
  {id:83,mainCategory:13,value:"Galamuna",label:"Galamuna"},
  {id:84,mainCategory:13,value:"Manampitiya",label:"Manampitiya"},
  {id:85,mainCategory:13,value:"Jayantipura",label:"Jayantipura"},
  {id:86,mainCategory:14,value:"Kaludewela",label:"Kaludewela"},
  {id:87,mainCategory:14,value:"Mandandawela",label:"Mandandawela"},
  {id:88,mainCategory:14,value:"Ukuwela",label:"Ukuwela"},
  {id:89,mainCategory:14,value:"Hulangamuwa",label:"Hulangamuwa"},
  {id:90,mainCategory:14,value:"Aluvihare",label:"Aluvihare"},
  {id:91,mainCategory:15,value:"Akurana",label:"Akurana"},
  {id:92,mainCategory:15,value:"Ambatenna",label:"Ambatenna"},
  {id:93,mainCategory:15,value:"Kadugannawa",label:"Kadugannawa"},
  {id:94,mainCategory:15,value:"Katugastota",label:"Katugastota"},
  {id:95,mainCategory:15,value:"Pilimatalawa",label:"Pilimatalawa"},
  {id:96,mainCategory:16,value:"Bopattalawa",label:"Bopattalawa"},
  {id:97,mainCategory:16,value:"Haggala",label:"Haggala"},
  {id:98,mainCategory:16,value:"Laxapana",label:"Laxapana"},
  {id:99,mainCategory:16,value:"Pattipola",label:"Pattipola"},
  {id:100,mainCategory:16,value:"Udapussallawa",label:"Udapussallawa"},
  {id:101,mainCategory:17,value:"Bulathkohupitiya",label:"Bulathkohupitiya"},
  {id:102,mainCategory:17,value:"Dehiovita",label:"Dehiovita"},
  {id:103,mainCategory:17,value:"Karawanella",label:"Karawanella"},
  {id:104,mainCategory:17,value:"Galigamuwa",label:"Galigamuwa"},
  {id:105,mainCategory:17,value:"Warakapola",label:"Warakapola"},
  {id:106,mainCategory:18,value:"Gomarankadawala",label:"Gomarankadawala"},
  {id:107,mainCategory:18,value:"Kantalai",label:"Kantalai"},
  {id:108,mainCategory:18,value:"Siripura",label:"Siripura"},
  {id:109,mainCategory:18,value:"Verugal",label:"Verugal"},
  {id:110,mainCategory:18,value:"Morawewa",label:"Morawewa"},
  {id:111,mainCategory:19,value:"Kiran",label:"Kiran"},
  {id:112,mainCategory:19,value:"Kattankudy",label:"Kattankudy"},
  {id:113,mainCategory:19,value:"Eravur",label:"Eravur"},
  {id:114,mainCategory:19,value:"Kokkadichcholai",label:"Kokkadichcholai"},
  {id:115,mainCategory:19,value:"Chenkalady",label:"Chenkalady"},
  {id:116,mainCategory:20,value:"Ampara",label:"Ampara"},
  {id:117,mainCategory:20,value:"Damana",label:"Damana"},
  {id:118,mainCategory:20,value:"Akkaraipattu",label:"Akkaraipattu"},
  {id:119,mainCategory:20,value:"Dehiattakandiya",label:"Dehiattakandiya"},
  {id:120,mainCategory:20,value:"Mahaoya",label:"Mahaoya"},
  {id:121,mainCategory:21,value:"Bibile",label:"Bibile"},
  {id:122,mainCategory:21,value:"Siyambalanduwa",label:"Siyambalanduwa"},
  {id:123,mainCategory:21,value:"Dombagahawela",label:"Dombagahawela"},
  {id:124,mainCategory:21,value:"Buddama",label:"Buddama"},
  {id:125,mainCategory:21,value:"Nakkala",label:"Nakkala"},
  {id:126,mainCategory:22,value:"Ella",label:"Ella"},
  {id:127,mainCategory:22,value:"Mahiyanganaya",label:"Mahiyanganaya"},
  {id:128,mainCategory:22,value:"Walimada",label:"Walimada"},
  {id:129,mainCategory:22,value:"Kandeketiya",label:"Kandeketiya"},
  {id:130,mainCategory:22,value:"Hali-Ela",label:"Hali-Ela"},
  {id:131,mainCategory:23,value:"Tangalle",label:"Tangalle"},
  {id:132,mainCategory:23,value:"Ambalantota",label:"Ambalantota"},
  {id:133,mainCategory:23,value:"Walasmulla",label:"Walasmulla"},
  {id:134,mainCategory:23,value:"Tissamaharama",label:"Tissamaharama"},
  {id:135,mainCategory:23,value:"Middeniya",label:"Middeniya"},
  {id:136,mainCategory:24,value:"Akuressa",label:"Akuressa"},
  {id:137,mainCategory:24,value:"Dickwella",label:"Dickwella"},
  {id:138,mainCategory:24,value:"Pasgoda",label:"Pasgoda"},
  {id:139,mainCategory:24,value:"Weligama",label:"Weligama"},
  {id:140,mainCategory:24,value:"Athuraliya",label:"Athuraliya"},
  {id:141,mainCategory:25,value:"Gintota",label:"Gintota"},
  {id:142,mainCategory:25,value:"Bope",label:"Bope"},
  {id:143,mainCategory:25,value:"Katugoda",label:"Katugoda"},
  {id:144,mainCategory:25,value:"Galwadugoda",label:"Galwadugoda"},
  {id:145,mainCategory:25,value:"Imaduwa",label:"Imaduwa"},
]

// 2nd form property
export const propertAdType = [
  {id:1,value:"For Rent",label:"For Rent"},
  {id:2,value:"For Sale",label:"For Sale"},
]

export const propertAdCategory = [
  {id:1,value:"Land",label:"Land"},
  {id:2,value:"House",label:"House"},
]

export const propertType = [
  {id:1,mainCategory:1,value:"Agricultural",label:"Agricultural"},
  {id:2,mainCategory:1,value:"Commercial",label:"Commercial"},
  {id:3,mainCategory:1,value:"Residential",label:"Residential"},
  {id:4,mainCategory:2,value:"Single Story",label:"Single Story"},
  {id:5,mainCategory:2,value:"Two Story",label:"Two Story"},
  {id:6,mainCategory:2,value:"Three Story",label:"Three Story"},
]



//Vehicle Data
export const vehicleType = [
  {id:1,value:"Cars",label:"Cars"},
  {id:2,value:"Vans",label:"Vans"},
  {id:3,value:"SUVs",label:"SUVs"},
  {id:4,value:"Lorry",label:"Lorry"},
  {id:5,value:"Threeweel",label:"Threeweel"},
  {id:6,value:"Motor Bicycle",label:"Motar Bicycle"},
  {id:7,value:"Jeep",label:"Jeep"},
]
export const manufacturer = [
  {id:1,value:"Suzuki",label:"Suzuki"},
  {id:2,value:"Toyota",label:"Toyota"},
  {id:3,value:"Nissan",label:"Nissan"},
  {id:4,value:"Tata",label:"Tata"},
  {id:5,value:"Bajaj",label:"Bajaj"},
  {id:6,value:"Honda",label:"Honda"},
  {id:7,value:"Isuzu",label:"Isuzu"},
  {id:8,value:"Mazda",label:"Mazda"},
  {id:9,value:"Mitsubishi",label:"Mitsubishi"},
  {id:10,value:"Micro",label:"Micro"},
  {id:11,value:"Mahindra",label:"Mahindra"},
]
export const modelTypes = [
  {id:1,mainCategory:1,value:"Swift",label:"Swift"},
  {id:2,mainCategory:2,value:"Vitz",label:"Vitz"},
  {id:3,mainCategory:3,value:"Sunny",label:"Sunny"},
  {id:4,mainCategory:1,value:"Alto",label:"Alto"},
  {id:5,mainCategory:6,value:"Vezel",label:"Vezel"},
  {id:6,mainCategory:11,value:"Maxximo",label:"Maxximo"},
  {id:7,mainCategory:11,value:"Bolero",label:"Bolero"},
  {id:8,mainCategory:3,value:"Caravan",label:"Caravan"},
  {id:9,mainCategory:2,value:"Hiace",label:"Hiace"},
  {id:10,mainCategory:2,value:"Hiace Dolphin",label:"Hiace Dolphin"},
  {id:11,mainCategory:5,value:"Platina",label:"Platina"},
  {id:12,mainCategory:5,value:"Discover",label:"Discover"},
  {id:13,mainCategory:5,value:"CT 100",label:"CT 100"},
  {id:14,mainCategory:1,value:"Wagon R",label:"Wagon R"},
  {id:15,mainCategory:4,value:"Nexon",label:"Nexon"},
  {id:16,mainCategory:4,value:"Mini Truck",label:"Mini Truck"},
  {id:17,mainCategory:6,value:"Hness CB350",label:"Hness CB350"},
  {id:18,mainCategory:7,value:"D-MAX",label:"D-MAX"},
  {id:19,mainCategory:8,value:"CX-5",label:"CX-5"},
  {id:20,mainCategory:9,value:"Pajero sport",label:"Pajero sport"},
  {id:21,mainCategory:10,value:"Panda",label:"Panda"},
]
export const condition = [
  {id:1,value:"Brand New",label:"Brand New"},
  {id:2,value:"Reconditioned",label:"Reconditioned"},
  {id:3,value:"Used",label:"Used"},
]

//Electronic Data
export const electronicCategory = [
  {id:1,value:"Cell phones-Accessories",label:"Cell phones-Accessories"},
  {id:2,value:"Cameras",label:"Cameras"},
  {id:3,value:"Audio & MP3",label:"Audio & MP3"},
  {id:4,value:"Kitchen, Home Applianas",label:"Kitchen, Home Applianas"},
  {id:5,value:"Laptops, Desktops & Hardware",label:"Laptops, Desktops & Hardware"},
  {id:6,value:"Networking, WiFi, & CCTV",label:"Networking, WiFi, & CCTV"},
  {id:7,value:"Software",label:"Software"},
  {id:8,value:"TVs",label:"TVs"},
  {id:9,value:"Video games",label:"Video games"},
  {id:10,value:"Other",label:"Other"},
]

export const eCondition = [
  {id:1,value:"Brand New",label:"Brand New"},
  {id:2,value:"Used",label:"Used"},
]
